channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.0
  - r-tidyverse
  - r-readr
  - r-tidyverse
  - r-RColorBrewer
  - r-pheatmap
  - r-ggplot2
  - r-ggrepel
  - bioconductor-DEGreport
  - bioconductor-tximport
  - bioconductor-DOSE
  - bioconductor-pathview
  - bioconductor-clusterProfiler
  - bioconductor-gage
  - bioconductor-gageData
  - bioconductor-DESeq2
