install.packages("readr")
install.packages("tidyverse")
install.packages("RColorBrewer")
install.packages("pheatmap")
install.packages("ggplot2")
BiocManager::install("DESeq2")
BiocManager::install("DEGreport")
BiocManager::install("tximport")
BiocManager::install("DOSE")
BiocManager::install("pathview")
BiocManager::install("clusterProfiler")
BiocManager::install("ggrepel")
BiocManager::install("gage")
BiocManager::install("gageData")

